# Generated by Django 6.0.7 on 2026-07-31 21:00

import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.vector
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, max_length=150)),
                ('website', models.URLField(blank=True)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('extra_info', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=255)),
                ('subscription_tier', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('title', models.TextField()),
                ('meeting_type', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.customer')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_1_report_persistent', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.customer')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='myapi.meeting')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.organisation')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='myapi.organisation'),
        ),
        migrations.CreateModel(
            name='TranscriptReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField()),
                ('summary', models.TextField()),
                ('merged_final_report', models.TextField()),
                ('transcript_search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('summary_search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('report_search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_report', to='myapi.meeting')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunks', models.TextField()),
                ('vector', pgvector.django.vector.VectorField(dimensions=1024)),
                ('metadata', models.JSONField(default=dict)),
                ('transcript_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='myapi.transcriptreport')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesperson_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.TextField()),
                ('role', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.user')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='myapi.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_report', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.customer')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='html_report', to='myapi.meeting')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.organisation')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.user')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='salesperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.user'),
        ),
        migrations.AddField(
            model_name='customer',
            name='salesperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='myapi.user'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['customer'], name='myapi_meeti_custome_befd8f_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['salesperson'], name='myapi_meeti_salespe_36d897_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['organisation'], name='myapi_meeti_organis_9778d1_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['meeting_date'], name='myapi_meeti_meeting_d80275_idx'),
        ),
    ]
