# Generated by Django 6.0.7 on 2026-08-05 11:33

import django.contrib.postgres.indexes
import pgvector.django.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['salesperson'], name='myapi_custo_salespe_8b87c7_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organisation'], name='myapi_custo_organis_6e4ad0_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_name'], name='myapi_custo_custome_a8b7cf_idx'),
        ),
        migrations.AddIndex(
            model_name='embedding',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['vector'], m=16, name='embed_vector_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['meeting_type'], name='myapi_meeti_meeting_53306e_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['customer', '-meeting_date'], name='myapi_meeti_custome_b1b0f4_idx'),
        ),
        migrations.AddIndex(
            model_name='meetinganalysis',
            index=models.Index(fields=['created_at'], name='myapi_meeti_created_cd28b6_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingreport',
            index=models.Index(fields=['created_at'], name='myapi_meeti_created_3142e7_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptreport',
            index=django.contrib.postgres.indexes.GinIndex(fields=['transcript_search'], name='myapi_trans_transcr_ddba6a_gin'),
        ),
        migrations.AddIndex(
            model_name='transcriptreport',
            index=django.contrib.postgres.indexes.GinIndex(fields=['summary_search'], name='myapi_trans_summary_f5d800_gin'),
        ),
        migrations.AddIndex(
            model_name='transcriptreport',
            index=django.contrib.postgres.indexes.GinIndex(fields=['report_search'], name='myapi_trans_report__8f5d3a_gin'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('organisation', 'customer_name'), name='unique_org_customer_name'),
        ),
    ]
