# Generated by Django 6.0.7 on 2026-08-05 20:43

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_customer_myapi_custo_salespe_8b87c7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transcriptreport',
            name='myapi_trans_transcr_ddba6a_gin',
        ),
        migrations.RemoveIndex(
            model_name='transcriptreport',
            name='myapi_trans_summary_f5d800_gin',
        ),
        migrations.RemoveIndex(
            model_name='transcriptreport',
            name='myapi_trans_report__8f5d3a_gin',
        ),
        migrations.AddField(
            model_name='embedding',
            name='chunk_search',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='embedding',
            index=django.contrib.postgres.indexes.GinIndex(fields=['chunk_search'], name='myapi_embed_chunk_s_112e7b_gin'),
        ),
        migrations.RemoveField(
            model_name='transcriptreport',
            name='report_search',
        ),
        migrations.RemoveField(
            model_name='transcriptreport',
            name='summary_search',
        ),
        migrations.RemoveField(
            model_name='transcriptreport',
            name='transcript_search',
        ),
    ]
