# Generated by Django 6.0.7 on 2026-08-05 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_remove_transcriptreport_myapi_trans_transcr_ddba6a_gin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 5, 22, 50, 28, 756863, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
