# Generated by Django 6.1.1 on 2026-10-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_image',
            field=models.ImageField(blank=True, null=True, upload_to='customer_photos/'),
        ),
    ]
